package com.danhuang.crop;

import java.io.Serializable;

public class Client implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.user_id
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.username
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.password
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table client
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.user_id
     *
     * @return the value of client.user_id
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.user_id
     *
     * @param userId the value for client.user_id
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.username
     *
     * @return the value of client.username
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.username
     *
     * @param username the value for client.username
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.password
     *
     * @return the value of client.password
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.password
     *
     * @param password the value for client.password
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }
}