package com.danhuang.crop;

import java.io.Serializable;

public class Kinds implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kinds.id
     *
     * @mbggenerated Mon Jul 01 08:55:51 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kinds.name
     *
     * @mbggenerated Mon Jul 01 08:55:51 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kinds.amount
     *
     * @mbggenerated Mon Jul 01 08:55:51 CST 2019
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kinds
     *
     * @mbggenerated Mon Jul 01 08:55:51 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kinds.id
     *
     * @return the value of kinds.id
     *
     * @mbggenerated Mon Jul 01 08:55:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kinds.id
     *
     * @param id the value for kinds.id
     *
     * @mbggenerated Mon Jul 01 08:55:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kinds.name
     *
     * @return the value of kinds.name
     *
     * @mbggenerated Mon Jul 01 08:55:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kinds.name
     *
     * @param name the value for kinds.name
     *
     * @mbggenerated Mon Jul 01 08:55:51 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kinds.amount
     *
     * @return the value of kinds.amount
     *
     * @mbggenerated Mon Jul 01 08:55:51 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kinds.amount
     *
     * @param amount the value for kinds.amount
     *
     * @mbggenerated Mon Jul 01 08:55:51 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}