package com.danhuang.crop;

import java.io.Serializable;

public class Status implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.id
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.name
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.barcode
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    private Integer barcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.price
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.total
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status.sold
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    private Integer sold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table status
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.id
     *
     * @return the value of status.id
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.id
     *
     * @param id the value for status.id
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.name
     *
     * @return the value of status.name
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.name
     *
     * @param name the value for status.name
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.barcode
     *
     * @return the value of status.barcode
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public Integer getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.barcode
     *
     * @param barcode the value for status.barcode
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public void setBarcode(Integer barcode) {
        this.barcode = barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.price
     *
     * @return the value of status.price
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.price
     *
     * @param price the value for status.price
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.total
     *
     * @return the value of status.total
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.total
     *
     * @param total the value for status.total
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status.sold
     *
     * @return the value of status.sold
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public Integer getSold() {
        return sold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status.sold
     *
     * @param sold the value for status.sold
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    public void setSold(Integer sold) {
        this.sold = sold;
    }
}