package com.danhuang.mapper;

import com.danhuang.crop.Status;
import com.danhuang.crop.StatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    int countByExample(StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    int deleteByExample(StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    int insert(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    int insertSelective(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    List<Status> selectByExample(StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    Status selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    int updateByExampleSelective(@Param("record") Status record, @Param("example") StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    int updateByExample(@Param("record") Status record, @Param("example") StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    int updateByPrimaryKeySelective(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status
     *
     * @mbggenerated Mon Jun 24 16:09:11 CST 2019
     */
    int updateByPrimaryKey(Status record);
}